/** Every visible string and accessible name of the tables plugin. `{x}` placeholders are filled in. */
export const TABLE_LABELS = {
  importCsv: "Import CSV",
  importCsvDescription: "Insert a table from a CSV or TSV file",
  toggleHeader: "Toggle header row",
  toggleHeaderDescription: "Turn the table's first row into a header row, or back",
  moveRowUp: "Move row up",
  moveRowDown: "Move row down",
  moveColumnLeft: "Move column left",
  moveColumnRight: "Move column right",
  resizeColumn: "Resize column {n}",
  pixels: "{n} pixels",
  rowGrip: "Drag to move this row",
  columnGrip: "Drag to move this column",
  column: "Column {n}",
  sortHint: "Sort",
  sortedAscending: "Sorted by {name}, ascending",
  sortedDescending: "Sorted by {name}, descending",
  sortCleared: "Original order",
  rowMoved: "Row moved to position {i} of {n}",
  columnMoved: "Column moved to position {i} of {n}",
  cannotMove: "It cannot move further",
  headerCannotMove: "The header row cannot move. Use Toggle header row instead.",
  headerOff: "Header row off: the first row is now a body row",
  headerOn: "Header row on",
  headerNothing: "There is no row to make the header",
  aligned: "Column aligned {a}",
  alignCleared: "Column alignment cleared",
  left: "left",
  center: "centre",
  right: "right",
  pasted: "Pasted a table with {rows} rows and {cols} columns",
  pastedCells: "Pasted {n} cells",
  truncated: "Only the first {rows} rows and {cols} columns were kept",
  imported: "Imported a table with {rows} rows and {cols} columns",
  tooLarge: "Import refused: the file is larger than {max}.",
  tooManyRows: "Import refused: the table has more than {max} rows.",
  tooManyColumns: "Import refused: the table has more than {max} columns.",
  empty: "Import refused: the file holds no table.",
  unreadable: "Import refused: the file could not be read.",
  dismiss: "Dismiss",
};

export type TableLabels = typeof TABLE_LABELS;

export const fmt = (s: string, v: Record<string, string | number>): string => s.replace(/\{(\w+)\}/g, (m, k: string) => (Object.prototype.hasOwnProperty.call(v, k) ? String(v[k]) : m));
