// The same package through `require`: the .d.cts declarations must resolve under node16.
import { createEditor, parse } from "advanced-texteditor-md";
import { texToMathML } from "advanced-texteditor-md/math";
import { BUILTIN_EMBEDS } from "advanced-texteditor-md/embeds";
import { highlightMark } from "advanced-texteditor-md/plugins";
import { htmlToMarkdown } from "advanced-texteditor-md/paste";
import javascript from "advanced-texteditor-md/highlight/javascript";
export const used = [createEditor, parse, texToMathML, BUILTIN_EMBEDS, highlightMark, htmlToMarkdown, javascript];
import { createAlertsPlugin } from "advanced-texteditor-md/alerts";
import en from "advanced-texteditor-md/i18n/en";
export const usedFeatures = [createAlertsPlugin, en];
import { createDefinitionListsPlugin, DEFINITION_LIST_SYNTAX } from "advanced-texteditor-md/deflists";
export const usedDeflists = [createDefinitionListsPlugin({ labels: { insert: "x" } }), DEFINITION_LIST_SYNTAX];
import { createTasks } from "advanced-texteditor-md/tasks";
export const usedTasks = [createTasks];
import { createPresentView, splitSlides } from "advanced-texteditor-md/present";
import { createReaderView } from "advanced-texteditor-md/reader";
import { createSnippets } from "advanced-texteditor-md/snippets";
export const usedSnippets = [createSnippets];
import { findLinks, createWikiLinks } from "advanced-texteditor-md/links";
export const usedLinks = [findLinks, createWikiLinks];
import { createCommentsPlugin } from "advanced-texteditor-md/comments";
export const usedComments = [createCommentsPlugin];
import { createFrontMatterPlugin } from "advanced-texteditor-md/frontmatter";
export const usedFrontMatter = [createFrontMatterPlugin];
export const usedViews = [createPresentView, splitSlides, createReaderView];
