/** Round-trip corpus: every entry must satisfy stringify(parse(stringify(parse(x)))) === stringify(parse(x)). */
const longLine = "word ".repeat(2000) + "*end*";
const deep = "> ".repeat(12) + "deep";
const nestedList = Array.from({ length: 8 }, (_, i) => "  ".repeat(i) + "- level " + i).join("\n");

export const CORPUS: string[] = [
  // --- trivial / whitespace
  "",
  "\n",
  "   \n\n  \n",
  "a",
  "a\n",
  "\n\n\na\n\n\n",
  "a\r\nb\r\n\r\nc",
  "a\rb",
  "\t\ttab only",
  "trailing spaces   \nnext",
  "two  \nspaces break",
  "backslash\\\nbreak",
  "end backslash\\",
  // --- headings
  "# H1",
  "## H2 ##",
  "### H3 #",
  "#### H4",
  "##### H5",
  "###### H6",
  "####### seven is text",
  "#nospace",
  "# ",
  "#",
  "# #",
  "# foo #bar",
  "# foo \\#",
  "Setext one\n===",
  "Setext two\n---",
  "multi\nline setext\n===",
  "# a\n# b\n\npara",
  "  ## indented heading",
  // --- paragraphs and inline
  "plain paragraph",
  "first\n\nsecond\n\nthird",
  "soft\nbreak\nlines",
  "*em* and _em_ and **strong** and __strong__",
  "***both*** and ___both___",
  "**bold *nested em* bold**",
  "*em **nested strong** em*",
  "***a** b*",
  "***a* b**",
  "*a**b*",
  "*a*_b_*c*",
  "**a****b**",
  "*****",
  "**unbalanced",
  "*unbalanced",
  "unbalanced**",
  "_ not em _",
  "* not em *",
  "snake_case_word and 2*3*4",
  "intra*word*emphasis",
  "foo*bar*",
  "*foo bar *",
  "** foo bar**",
  "a * b * c",
  "*(emphasis)*",
  "**foo**bar",
  "__foo__bar",
  "~~strike~~ and ~~**bold strike**~~",
  "~single~ tilde",
  "~~~",
  "~~ no close",
  "a ~~b~~ c ~~d",
  "`code` and ``double ` tick`` and ` spaced `",
  "`` ` ``",
  "``` triple inline ```",
  "`unclosed",
  "``unclosed`",
  "`a`b`c`",
  "`code with *stars*`",
  "\\*not em\\*",
  "\\\\ double backslash",
  "\\a not an escape",
  "escapes: \\` \\* \\_ \\[ \\] \\( \\) \\# \\+ \\- \\. \\! \\| \\~ \\$",
  "entity &amp; &lt; &gt; &quot; &#35; &#x41; &copy; &bogus; &amp",
  "literal \\&amp; stays",
  "&lt;script&gt;alert(1)&lt;/script&gt;",
  "<div>raw html</div>",
  "<script>alert(1)</script>",
  "text <b>bold</b> text",
  "a < b > c",
  "<not a tag",
  "<https://example.com>",
  "<mailto:a@b.co> and <a@b.co>",
  "\\<https://example.com>",
  "<!-- comment -->",
  // --- links
  "[link](http://example.com)",
  "[link](http://example.com \"title\")",
  "[link](<http://example.com/a b> 'title')",
  "[link](http://example.com/a_(b))",
  "[link](http://example.com/a(b)c)",
  "[link](http://example.com/\\(x)",
  "[link]()",
  "[](http://empty-text.com)",
  "[a [nested] b](http://x.com)",
  "[a](http://x.com) [b](http://y.com)",
  "[*em* **strong** `code`](http://x.com)",
  "[link with ] bracket](http://x.com)",
  "[ref][r1] and [r2] and [text][]\n\n[r1]: http://one.com\n[r2]: <http://two.com> \"Two\"\n[text]: http://three.com",
  "[undefined ref][nope]",
  "[foo]: /url \"title\"\n\n[foo]",
  "[Foo Bar]: /url\n\n[foo   bar]",
  "bare http://example.com url",
  "bare https://example.com/path?q=1&b=2. end",
  "(see https://example.com/a_(b))",
  "www.example.com and www.x.co/path,",
  "http://",
  "https://a",
  "wwwx.com no",
  "*https://example.com*",
  "[https://example.com](https://example.com)",
  "[www.example.com](http://www.example.com)",
  "[x](javascript:alert(1))",
  "[x](  /relative  )",
  "[x](#hash) [y](?q=1) [z](./rel/path.md)",
  "![alt](http://img.com/a.png)",
  "![alt *em*](a.png \"t\")",
  "![](empty.png)",
  "![a][img]\n\n[img]: pic.png",
  "![broken](",
  "[![inner](i.png)](http://x.com)",
  // --- chips / mentions
  "[@Jane Doe](mention:person/123?clickup=456&hub=789)",
  "[@Jane](mention:abc)",
  "[#12 Fix bug](task:issue/12)",
  "[Task](task:issue/12)",
  "[@A/B?C](mention:person/a%2Fb%3Fc)",
  "[@x](mention:person/a%28b%29?k=%26%3D%25)",
  "hello [@Jane](mention:person/1) and [@Bob](mention:person/2).",
  "[no trigger](mention:person/9)",
  "[@](mention:person/9)",
  "[@Jane](mention:person/%E4%BD%A0)",
  // --- block quote
  "> quote",
  "> a\n> b",
  "> a\nlazy",
  "> a\n\n> b",
  "> # heading\n> text",
  "> - list\n> - items",
  "> > nested\n> back",
  deep,
  ">",
  "> ",
  "> ```\n> code\n> ```",
  "> a\n>\n> b",
  // --- lists
  "- a\n- b\n- c",
  "* a\n* b",
  "+ a\n+ b",
  "- a\n* b\n+ c",
  "1. one\n2. two\n3. three",
  "1) one\n2) two",
  "5. five\n6. six",
  "0. zero\n1. one",
  "1. a\n1. b\n1. c",
  "1. a\n\n   b\n2. c",
  "- a\n\n- b\n\n- c",
  "- a\n\n  b\n- c",
  "- a\n  - b\n    - c\n  - d\n- e",
  nestedList,
  "- a\n    - four space nested",
  "1. a\n   - b\n   - c\n2. d",
  "- a\n  continued lazily\nlazy again",
  "- item\n\n  ```js\n  code\n  ```\n- next",
  "- item\n  ```\n  tight code\n  ```",
  "- a\n  > quote in item",
  "-\n- empty first",
  "- \n- b",
  "-",
  "- [ ] todo\n- [x] done\n- [X] done caps",
  "- [ ]\n- [x]",
  "- [ ] a\n  - [x] nested",
  "1. [ ] ordered task",
  "- [link](x) [ ] not a task",
  "- [] not task\n- [y] nope",
  "- # heading in item",
  "- a\n\n\n- b",
  "- a\n\n\n\npara after",
  "- a\n- b\n\npara after\n\n- new list",
  "* * *",
  "- - -",
  "- ---",
  "1. - nested bullet in ordered",
  "text\n- list interrupts",
  "text\n2. not interrupt\n3. same",
  "text\n1. interrupt",
  "- a\n\n      indented code in item",
  "10. ten\n11. eleven",
  "999999999. big",
  "1234567890. too big",
  // --- code
  "```\ncode\n```",
  "```js\nconst a = 1;\n```",
  "```js title=\"x\"\nlet y\n```",
  "~~~\ntilde\n~~~",
  "~~~py\nprint(1)\n~~~",
  "````\n```\ninner\n```\n````",
  "```\nunclosed fence\nstill code",
  "```\n\nblank lines\n\n```",
  "```\n```",
  "``` `bad info`\nnot a fence",
  "    indented code\n    more",
  "    indented\n\n    after blank",
  "para\n\n    code\n\npara",
  "para\n    not code (lazy)",
  "```\n    keeps indentation\n  and this\n```",
  "  ```\n  indented fence\n  ```",
  "```\n<script>alert(1)</script>\n```",
  "- ```\n  in list\n  ```",
  // --- hr
  "---",
  "***",
  "___",
  "- - -\n\ntext",
  "text\n\n---\n\ntext",
  "text\n***\ntext",
  "--",
  "----------",
  // --- tables
  "| a | b |\n|---|---|\n| 1 | 2 |",
  "a | b\n--|--\n1 | 2",
  "| left | center | right |\n|:---|:---:|---:|\n| 1 | 2 | 3 |",
  "| a |\n|---|\n| x |",
  "| esc \\| pipe | b |\n|---|---|\n| `a\\|b` | c |",
  "| a | b |\n|---|---|\n| only one |",
  "| a | b |\n|---|---|\n| 1 | 2 | 3 | 4 |",
  "| **bold** | [l](http://x.com) |\n|---|---|\n| *em* | `code` |",
  "| a | b |\n|---|---|\n| 1 | 2 |\n\ntext after",
  "| a | b |\n|---|---|\n| 1 | 2 |\ntext row",
  "| a | b |\n|---|---|",
  "|a|b|\n|-|-|\n||x|",
  "| a | b |\n| - | - |\n|  |  |",
  "not | a table\nno delimiter row",
  "| a | b |\n|---|\n| 1 | 2 |",
  "- | a | b |\n  |---|---|\n  | 1 | 2 |",
  "> | a | b |\n> |---|---|\n> | 1 | 2 |",
  "para\n| a | b |\n|---|---|",
  // --- math
  "inline $x^2$ math",
  "$a+b$ and $c$",
  "costs $5 and $6 total",
  "$5",
  "$",
  "$$",
  "a $ b $ c",
  "$ x$ and $y $",
  "$1,000.00$",
  "price: $10, $20.50 and $300",
  "$x$5",
  "\\$x\\$",
  "$a\\$b$",
  "$$\nE = mc^2\n$$",
  "$$ x + y $$",
  "$$\n\\begin{aligned}\na &= b\n\\end{aligned}\n$$",
  "$$\nunclosed",
  "text\n\n$$\nx\n$$\n\ntext",
  "$$x$$ inline double",
  "$$$ triple",
  "- $$\n  x\n  $$",
  "```\n$not math$\n```",
  "`$not math$`",
  // --- footnotes
  "text[^1]\n\n[^1]: the note",
  "text[^a] more[^b]\n\n[^a]: A\n[^b]: B",
  "[^1]: multi\n    paragraph\n\n    second para",
  "ref[^missing] with no definition",
  "[^1]: orphan definition",
  "[^1]: a\n[^2]: b\n\ntext[^2][^1]",
  "[^note]: with `code` and *em*\n\ntext[^note]",
  // --- custom syntax-like text (plain parser must keep it literal)
  "::: note\ncontent\n:::",
  "==marked== text",
  "a === b == c",
  // --- unicode / emoji / misc
  "emoji \uD83D\uDE00 text",
  "**\uD83D\uDE00 bold emoji**",
  "\u00e9l\u00e8ve caf\u00e9 \u4f60\u597d\u4e16\u754c",
  "*\u4f60\u597d*\u4e16\u754c",
  "\u0645\u0631\u062d\u0628\u0627 \u0628\u0627\u0644\u0639\u0627\u0644\u0645",
  "nbsp\u00a0here and \u200bzero width",
  "a\u2028b",
  "\uD83D\uDC68\u200D\uD83D\uDC69\u200D\uD83D\uDC67 family",
  // --- nasty mixes
  "[a](b)[c](d)[e](f)",
  "*[a](http://x.com)* and **[b](http://y.com)**",
  "[**a**](http://x.com)",
  "`a`*b*`c`",
  "# *em* heading with `code` and [link](x)",
  "- **bold** item with [link](http://x.com) and `code`",
  "1. *a*\n2. **b**\n3. ~~c~~",
  "> **quote** with [link](x)\n> - and list",
  "text with | pipe and * star and _ under and ` tick and # hash",
  "# heading\ntext right after\n- list right after\n> quote right after\n```\ncode\n```\n---\n| a | b |\n|---|---|",
  "line one\\\nline two\\\nline three",
  "a  \nb  \nc",
  "*a\nb*",
  "**a\nb**",
  "[a\nb](http://x.com)",
  "`a\nb`",
  "<div>\n\n*not html*\n\n</div>",
  "1. a\n- b",
  "- a\n1. b",
  "&#0; &#xD800; &#99999999;",
  longLine,
  "a".repeat(5000),
  "*".repeat(300),
  "_".repeat(301),
  "[".repeat(200) + "]".repeat(200),
  "(".repeat(100) + ")".repeat(100),
  "`".repeat(50),
  "- ".repeat(50),
  "> ".repeat(50),
  "# ".repeat(20),
];
